### PR TITLE
33 fe modal for change user data

### LINKED ISSUE #33: FE - Modal for change user data
I guess I can right now implement modal, which will be the interface to change the data, will not send anything to BE yet though, as there are functions to implement for that.

### PR DESCRIPTION
**Pull request by janmrakava**
It's foggy and nasty outside, so I have to work on this project :) 

Desktop: 
Screenshot 2024-11-10 at 11 31 09

Mobile: 
Screenshot 2024-11-10 at 11 31 48

### CODE REVIEW

**Comment by prikryla** [comment]
@janmrakava I don't wanna bother you but I'm not sure if this approach is user friendly. Why we should display another window with single input? My idea - once user open it's profile, there should be some button like "Edit profile" where user can edit the current data as name, email. WDYT? Or is there any reason why should we display this window?

**Comment by janmrakava** [comment]
Well, I don't know what to say :) I'm just follow the design in Figma, what our designer designed (that's me, sorry :D), I can change it, no problem I guess. Just need the design for that, or at least some prototype, because right now I don't understand your idea

**Comment by prikryla** [comment]
Alright, just leave it there for now, it's not a big deal and we can improve it later. 
Sorry, let's say that if you design Figma, we can approve something but when you really develop the stuff and think of that differently, some changes comes to your mind.

**Review by prikryla — APPROVED** [review]
Approved. Nice job. This edit process will be discussed later.

**Comment by janmrakava** [comment]
I didn't mean to sound offensive, I'm just saying that's how I did it when I did the design. I researched other sites differently, each one has it differently, I liked this approach. If you describe more how you thought about it, it may change. However, I think this functionality will probably be the least used in our application :)

**Comment by prikryla** [comment]
I understand and yes, for now it won't be necessary to change email or so.
What I mean with the design change. I will try to explain it in detail.

If you open your profile, you can see your profile picture and 3 imputs - username, email, password. What you designed and suggesting is that there should be another popup window where you can simply edit your username or email and submit the change with some button. How about to have some "Edit" button under those 3 inputs and once you'll need update your email or anything, you can do it just in those inputs that you already have it on your profile. It's unwanted to have such popup window basically with the same input and functionality in the profile section. Is it clear for now?

**Comment by janmrakava** [comment]
So this is where the misunderstanding arises :) When you open your profile, you may see three inputs - username, email, password. But that's not the case, they are elements that may look like that, but are only used to display to text, the user can click, highlight or I don't know what, but they can't change the values. He can only change the value through those popups. Maybe you can try pull the branch and try yourself

**Comment by janmrakava** [comment]
@prikryla I know you don't have much time, but maybe I'll close this here, mergnul at I can try your routs :)

**Comment by prikryla** [comment]
Based on you comment above - this is something that should be improved right? It's better to explain this in person I guess because we do not understand each other. Let's have a sync call where we could finally agree on something. WDYT?

**Comment by janmrakava** [comment]
@prikryla I guess we'll just have to, when?

**Comment by prikryla** [comment]
@janmrakava How about today's evening? Are you available?

**Pull request merged**
